### ISSUE TITLE
Poloniex client side authentication flow

### ISSUE THREAD

**Issue by einsteinx2** [balancemymoney/balance-open#10]
I'm not familiar with the API to I'll leave the details to @wolffan. This issue is to track whatever is needed to complete an authentication on the client side. An authenticate function in the PoloniexApi struct, plus whatever else is needed.

**Comment by wolffan** [comment]
This is already done on poloniex-xc9 #60

**Comment by wolffan** [comment]
Poloniex doesn't have an "account" per se, we just hit the endpoint with specific parameters, unsure if the institution applies and how to use it...

**Comment by einsteinx2** [comment]
Done
