### ISSUE TITLE
Fix login item add/remove

### ISSUE THREAD

**Issue by ricburton** [balancemymoney/balance-open#105]
<img src='https://shipusercontent.com/2ef5f28fbf77f0e6864f898f39793b59/Screen%20Shot%202017-08-30%20at%2014.01.37.png' title='Screen Shot 2017-08-30 at 14.01.37.png' width=532>

**Problem**
When I tried to uncheck the start on login check, I get this error.

I am guessing this is due to the change in app name?

**Comment by einsteinx2** [comment]
There's a lot of reasons this could happen... Were you running from Xcode or from /Applications? I'm not sure the login item stuff works correctly from Xcode.

Also, some things have changed in the highlander branch. We'll need to test this.

**Comment by einsteinx2** [comment]
Generalized the title to remove the dupe ticket.

**Comment by wolffan** [comment]
➤ Ben Baron commented:

Turns out the bundle ID for the helper app was wrong in the code, that's why it failed.
