### ISSUE TITLE
GDAX + Polo + Merge Bal & Balance Open

### ISSUE THREAD

**Issue by wolffan** [balancemymoney/balance-open#111]
- [x] If wrong key/secret is intro in Poloniex we're not failing properly (we add the account empty) (needs to throw errors)
- [x] Deleting an account freezes the add/remove screen on Preferences
- [x] GDAX login with wrong credentials leaves the app blocked in an unusable state and requires to relaunch
- [x] Update GDAX tests (one is failing after api changes for reporting to UI)

**Comment by wolffan** [comment]
OK
I managed to get both GDAX and Poloniex login errors consistently "sorted"

BUT atm the feedback is not the best (the error info is not very meaningful)
<img width="400" alt="screen shot 2017-09-05 at 12 12 42" src="https://user-images.githubusercontent.com/1092080/30056603-a2830daa-9233-11e7-932b-7e1106c5c127.png">

**Comment by wolffan** [comment]
Sorted, the account problem is only when we where creating empty/incorrect accounts

**Comment by ricburton** [comment]
🗝👍🤖🙏
