### ISSUE TITLE
Sign up view still shows old Plaid text

### ISSUE THREAD

**Issue by einsteinx2** [balancemymoney/balance-open#119]

**Comment by wolffan** [comment]
Not sure I have to remove the lock as well
<img width="385" alt="screen shot 2017-09-21 at 16 47 14" src="https://user-images.githubusercontent.com/1092080/30702207-99173136-9eec-11e7-8d69-85fbbaf8be60.png">

**Comment by wolffan** [comment]
Fixing this as well on #115

**Comment by wolffan** [comment]
This can be closed when the branch is merged
