### ISSUE TITLE
Rearranging accounts changes cell height

### ISSUE THREAD

**Issue by christianbaroni** [balancemymoney/balance-open#123]
If you rearrange a few accounts, it sometimes doubles the height of one of the account cells. Unsure how to reproduce reliably—I saw it twice dragging accounts around.

Both times I had the accounts settings window open. Not sure if there's a correlation.

![screen shot 2017-09-14 at 4 43 40 pm](https://user-images.githubusercontent.com/7061887/30455193-f85e222e-996c-11e7-9d93-7a95617cdd1c.png)

**Comment by einsteinx2** [comment]
I couldn't reproduce until I opened account prefs, then it happened on the second attempt. Probably some kind of race condition. Debugging now.

**Comment by einsteinx2** [comment]
Fixed
