### ISSUE TITLE
Currency price API backend support

### ISSUE THREAD

**Issue by einsteinx2** [balancemymoney/balance-open#125]
To facilitate currency displays, we need to pull the latest currency prices from the various exchanges and store them server side. Then the app can make one call to our server to pull all the latest prices at once. We can then update prices once a minute or even more often without hammering those APIs from thousands of clients.

**Comment by einsteinx2** [comment]
I've started collecting all of the API calls for exchange rates. Currently have a Paw file with Coinbase/GDAX, Bitfinex, and Kraken.

Now looking into fiat currencies. Forex doesn't seem to have an exchange rate API. XE has one that costs $1200/yr for "real time" aka updated every 60 seconds. Then there are various free ones that update daily.

I think XE is pretty much the gold standard for currency traders, so we should probably just use their API and pull once a minute and just use them for fiat currencies. 

From their site:
> XE gathers rates from over 100 sources to deliver every world currency through one simple API. Our currency data is so reliable, that it’s used by major corporations and government agencies all over the world.

Also, each one of the crypto exchanges seems to have at least some support for showing the prices in various currencies, though it would take multiple API calls. We need to decide if we want to just standardize all of our crypto prices to one currency, then use XE to convert from there, or if we want to use the prices from the exchanges (which may differ slightly). Maybe we should pull the big three: USD, EUR, GBP from all crypto exchanges that support it, then fill in the gaps with XE.

**Comment by einsteinx2** [comment]
Hmm actually I just realized that their API is for individual conversions, not exchange rates. They have a separate product for what we need. From their site:

>Need to download rates to store or cache?
XE offers flexible data delivery solutions. If you need to download currency rates to store on your computer or server, contact us.

So the pricing is probably a lot higher. I'll email them inquiring about the pricing. If it's unreasonable, we should just use a free API for daily updated fiat data as it doesn't change that fast anyway.

**Comment by einsteinx2** [comment]
This one also looks interesting, though they we're not allowed to "redistribute" it, which would mean we couldn't use it in this API without some kind of app verification I assume: 
https://1forge.com/forex-data-api/pricing

This one looks great for a free API, data updated daily:
http://fixer.io

**Comment by einsteinx2** [comment]
Looks like there are MANY fiat exchange rate APIs, both free and paid. This one also looks decent: https://openexchangerates.org/signup

Honestly I don't think fiat is volatile enough for it to really matter who we use, as long as we're getting data from a reliable source at least once a day.

**Comment by wolffan** [comment]
Poloniex has a free currency api. I can include on the Poloniex api

**Comment by einsteinx2** [comment]
Yep, already done a ton of work on this, it will be on the server side. Check out the branch I made in the balance-server repo. It has all the api urls in it. Just needs the stub methods filled in which I’ll get done today.

**Comment by einsteinx2** [comment]
Done today!
