### ISSUE TITLE
Xcode 9 build issues with Team

### ISSUE THREAD

**Issue by cjdowner** [balancemymoney/balance-open#127]
I've re-cloned the repository and am trying to build the app in Xcode 9 (beta 5), but am getting two build errors:

> 🛑 Code Signing Error: No account for team "Q4G66XSS36". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials. 

I've switched the team signing profile to my own, personal one (that contains macOS signing certificates) here, so not sure why this error is appearing...

> 🛑 Code Signing Error: No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "Q4G66XSS36" with a private key was found.

Obviously related to the first error, but worth noting.

<img width="488" alt="screen shot 2017-09-16 at 15 14 14" src="https://user-images.githubusercontent.com/2099705/30513757-a8c7180c-9b00-11e7-8560-cb60850827a5.png">

**Comment by wolffan** [comment]
@cjdowner are you a mac developer? (ios and mac have two different programs, both need to be paid)

**Comment by wolffan** [comment]
I don't have a mac dev account (only iOS)

<img width="504" alt="screen shot 2017-09-21 at 12 42 30" src="https://user-images.githubusercontent.com/1092080/30692095-6263095c-9eca-11e7-943a-de86be9ad152.png">

**Comment by wolffan** [comment]
i'll close this one  <3
