### ISSUE TITLE
Able to unlock without password when password protection is configured

### ISSUE THREAD

**Issue by pmoles** [balancemymoney/balance-open#128]
**System info:**
- Macbook Pro early 2011 w/ macOS 10.12.6
- Balance v0.9.3

**Repro steps:**

1. Open Balance
2. Go to Preferences > Security
3. Configure password protection
4. Close app (focus out the popup)
5. Open again and without typing anything click on the Unlock button
6. App is unlocked

**Notes:**
- When using the Enter key in the unlock screen, it does validate the password

**Comment by einsteinx2** [comment]
Good catch, we’ll get this fixed ASAP

**Comment by einsteinx2** [comment]
Fixed
