### ISSUE TITLE
Truncate crypto amounts at $0.01 precision

### ISSUE THREAD

**Issue by christianbaroni** [balancemymoney/balance-open#142]
Should we truncate crypto amounts when they surpass $0.01 precision (1 cent in native currency)? Thinking in the accounts view and maybe transactions. When sending/converting you should probably see exact amounts.

For BTC with $xxxx.xx value, .000001 is sufficient
For ETH with $xxx.xx value, .00001
For LTC with $xx.xx value, .0001
For LSK with $x.xx value, .001
etc.

Maybe one additional decimal place?

**Comment by christianbaroni** [comment]
Maybe ensure a minimum of 2 decimal places when available?

**Comment by christianbaroni** [comment]
Not sure how much work this would be, but I think it would make everything easier to look at and parse.

**Comment by einsteinx2** [comment]
Once we have the conversion function in place this is trivial to do

**Comment by wolffan** [comment]
could we move this to 1.1?

**Comment by einsteinx2** [comment]
Yep moving now.

**Comment by wolffan** [comment]
You mean if a token is 1.59832642 and we actually have 0.39€ 
To show 1.59 tokens instead of all the length?
We should just do this for all crypto? @einsteinx2  @christianbaroni
