### ISSUE TITLE
When adding an institution, it's not pulling the accounts until next sync

### ISSUE THREAD

**Issue by einsteinx2** [balancemymoney/balance-open#153]
During the add process, before completing, it should do an accounts and transactions pull so we can show everything in the UI immediately.

**Comment by wolffan** [comment]
Have you confirmed this? I been able to see an account when you see the accounts ui

**Comment by einsteinx2** [comment]
I've seen this with Kraken and at least one other.

**Comment by wolffan** [comment]
@einsteinx2 I can add a Kraken account and shows straight away on the UI... maybe it's fast refresh but...

**Comment by einsteinx2** [comment]
Seems to only be an issue with my Kraken account, and even after syncing I'm not getting anything actually so sounds like it's not an issue specifically when adding.
