### ISSUE TITLE
[macOS] When syncing, incorrect permissions should prompt the user to reconnect

### ISSUE THREAD

**Issue by einsteinx2** [balancemymoney/balance-open#157]
In my case, I added Coinbase before we added transaction support (like many of our testers have I assume). When I sync, it just silently fails.

Any time we get a permissions issue with any exchange, we need to mark the institution as passwordInvalid (or even better, replace that with something more descriptive) so the UI shows the reconnect dialog.

**Comment by einsteinx2** [comment]
Pretty sure it's happening with my other accounts also as I have 0 transactions.

**Comment by wolffan** [comment]
This applies to  any exchange (most of them you have to set specific permissions for transactions/visualization).
I think I added some of this to Poloniex, but the error codes will be different based on exchange.
We need to:

- [ ]  Identify error codes or errors to match incorrect permissions (for every data service)

- [ ] Add logic to detect and provide feedback to user

- [ ] At account add some piece of help (in an ? icon, explaining permissions)

**Comment by einsteinx2** [comment]
Working on this now since it's caused a lot of user confusion

**Comment by einsteinx2** [comment]
First pass done for macOS, but needs more work and testing.

**Comment by einsteinx2** [comment]
Done and tested for coinbase, mostly done for the others. Bumping the rest to 1.0.1

**Comment by einsteinx2** [comment]
Actually Eli will finish this when he's done with the iOS implementation

**Comment by cerezo074** [comment]
only kraken is missing for validation because server is out due by maintenance, other exchanges works well. This issue depends on implementation of #379, which add the refresh for other accounts different than coinbase when an account is reconnected.

**Comment by cerezo074** [comment]
All exchanges were tested and works well(including kraken). This feature needs #379 to works well because it containts the implementation for update an exchange when is different than coinbase. @einsteinx2 this feature would be done when #379 is merged because both use the same data models(shared code).
