### ISSUE TITLE
Can't add Bitcoin Addresses

### ISSUE THREAD

**Issue by mrarfarf** [balancemymoney/balance-open#159]
Hello!

Love the app, but I use bittrex, and when adding an address with a bitcoin address, it shows an error related to ETH addresses. Can you please build in a function to either select btc or eth addresses, or automatically differentiate between the two and use the correct service?

Thank you!

**Comment by wolffan** [comment]
Hello @mrarfarf thanks for reporting.
The address support for now is for ERC20 compatible tokens.
We will be adding support in the future

**Comment by einsteinx2** [comment]
As @wolffan said, we're working on adding support for Bitcoin addresses as well. In the meantime, we'll make it clearer in the UI that this is for Ethereum addresses only.

**Comment by einsteinx2** [comment]
This is covered by another issue and almost finished.
