### ISSUE TITLE
Cut off when re-positioned on the toolbar

### ISSUE THREAD

**Issue by gomesphoto** [balancemymoney/balance-open#161]
Reported on slack, when you re-position the BalanceOpen icon to the very right of the toolbar, the expanded view gets cut off by the screen. 

Check the screenshot bellow:

![22627566_147404335996305_1253239167_n](https://user-images.githubusercontent.com/10136079/31675616-118ab9b0-b35d-11e7-89b5-7ab3fe3acef3.png)

**Comment by wolffan** [comment]
Ok got a fix, but for now rough 
<img width="202" alt="screen shot 2017-10-20 at 16 38 00" src="https://user-images.githubusercontent.com/1092080/31826361-222b60c6-b5b5-11e7-85c7-3b84e9616c43.png">

**Comment by wolffan** [comment]
The lib needs lot more work to reposition the arrow
