### ISSUE TITLE
Capitalise the ticker's name

### ISSUE THREAD

**Issue by cjdowner** [balancemymoney/balance-open#164]
On adding a wallet to Balance, my currencies that are contained within there appear as `Eth`, etc - with only the first letter of the ticker capitalised. It would look a lot cleaner, and more consistent if it appeared as `ETH`.

Could be a bit tricky to fix as the ticker name may be something like `Eth Wallet`, or less than three characters - but those are more QA notes than anything.

**Comment by einsteinx2** [comment]
At first I assumed you were just using an old build, but I'm reproducing this in the latest code. It should say Ether there like it does for other institutions.

Adding a screenshot to show the difference, note that under Test Address it should say Ether like it does for Kraken and Poloniex.

Assigning to Raimon as this is Ethplorer related as well.


<img width="419" alt="screen shot 2017-10-18 at 3 37 36 pm" src="https://user-images.githubusercontent.com/350423/31741567-563475d4-b41a-11e7-9930-efd01331ec00.png">

**Comment by cjdowner** [comment]
That's the issue. Yep, this was discovered on the public beta.

That's looking so nice btw :)

**Comment by einsteinx2** [comment]
Yep it’s getting there! Fonts and spacing are not final at all, but we’re getting close!!

**Comment by wolffan** [comment]
This PR solves the issue: https://github.com/balancemymoney/balance-open/pull/175
