### ISSUE TITLE
When adding an account, we need to link to instructions on how to get make the api key

### ISSUE THREAD

**Issue by einsteinx2** [balancemymoney/balance-open#166]
A few testers have created keys with incorrect permissions. We need to have a button/link to get information on creating the key that links to a help page with screenshots. This goes for all exchanges except Coinbase.

* [x] Make a guide for Kraken
* [x] Make a guide for Poloniex
* [x] Make a guide for Bitfinex
* [x] Make a guide for Gdax
* [ ] UI link to guide

**Comment by wolffan** [comment]
Guides on wiki https://github.com/balancemymoney/balance-open/wiki

**Comment by einsteinx2** [comment]
Closing this issue as the instructions are created, we have another ticket for skinning the add account view:

Finish skinning add account view #334
