### ISSUE TITLE
Write Issue and Pull Request template

### ISSUE THREAD

**Issue by pedrouid** [balancemymoney/balance-open#170]
It would be good add to templates for when creating a new issue or starting a new pull request, as more contributors get involved and there are more features, it's important to have a clear structure of the minimum required information to solve an issue or know more about an enhancement or feature request.

Documentation for how to structure templates for Isuess and Pull Requests on Github is available here:
https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by wolffan** [comment]
Done
