### ISSUE TITLE
ETH txs don't seem to accurately update each hour

### ISSUE THREAD

**Issue by kristinatauch** [balancemymoney/balance-open#177]
user feedback

**Comment by wolffan** [comment]
@kristinatauch that is for ETH token or for wallet txs?

**Comment by einsteinx2** [comment]
Can you confirm what exchange this was or if it was a raw ether wallet address and also what "accurately" means exactly? Thanks!

**Comment by kristinatauch** [comment]
MyEtherWallet isn’t refreshing properly. The attached image shows two tokens that don’t exist in that wallet any more. There are other examples right after a fresh sync too.

<img width="405" alt="screen shot 2017-11-01 at 9 42 44 am" src="https://user-images.githubusercontent.com/30265438/32337597-b6c79816-bff2-11e7-914f-ce83f660e0a7.png">

**Comment by wolffan** [comment]
➤ Raimon Lapuente commented:

@kristinatauchmannova1 known issue (but with all wallet services)
