### ISSUE TITLE
"we've detected a new token in your wallet, would you like to add"

### ISSUE THREAD

**Issue by kristinatauch** [balancemymoney/balance-open#183]
user feedback: "we've detected a new token in your wallet, would you like to add" - i see this being important as more and more airdrops of random things I don't really care about happen

**Comment by wolffan** [comment]
@kristinatauch we use a service that adds tokens way sooner than any wallet and happens automatically. (even if they don't give the $ equivalent).
So you'll see your tokens when they are added (ethplorer and etherscan are more or less as fast).
I'd say we can close this...

**Comment by einsteinx2** [comment]
Agreed. We automatically show all new tokens even on exchanges, no need for a user action.
