### ISSUE TITLE
Popover arrow placement is broken on multiple monitor setups

### ISSUE THREAD

**Issue by einsteinx2** [balancemymoney/balance-open#197]
Seems to only calculate correctly on the main screen, not the current screen.

**Comment by einsteinx2** [comment]
Yep confirmed it's always the secondary monitor. The bug seems to be that the last screen coordinates to window coordinates doesn't work properly for the secondary screen (macOS bug or status bar bug apparently).

Changing the logic to try and remove the need for that bit, as it does correctly detect the current screen and status item location.

**Comment by einsteinx2** [comment]
Putting this aside for now to work on the cards UI as that's more important.

**Comment by einsteinx2** [comment]
Bumped cards to 1.1 as it will take more work than we have time for in 1.0. Trying to get this sorted now.

**Comment by wolffan** [comment]
➤ Ben Baron commented:

Fixed
