### ISSUE TITLE
GDAX/Kraken balances are still wrong

### ISSUE THREAD

**Issue by einsteinx2** [balancemymoney/balance-open#202]
From Tom K:

GDAX balances are still wrong (BTC balance doesn’t reflect recent change, cash balance is negative, which it never was).

**Comment by wolffan** [comment]
is it possible that we have similar error as coinbase where the token wasn't being refreshed?

**Comment by einsteinx2** [comment]
No because GDAX uses API keys that you create in account settings like Poloniex/Kraken/Bitfinex, it doesn't use the OAuth model like Coinbase does.

**Comment by wolffan** [comment]
➤ Raimon Lapuente commented:

I'll move this to done as I haven't seen any problems with this

**Comment by TomKotecki** [comment]
I reported this originally, and it's still happening with the latest build. While I moved everything out of GDAX lately, it's now Kraken (where I consolidated) which shows negative balances.

**Comment by einsteinx2** [comment]
@wolffan let's work with @TomKotecki on Slack to resolve this for good.
