### ISSUE TITLE
Have an adjustable height for the window

### ISSUE THREAD

**Issue by cjdowner** [balancemymoney/balance-open#205]
Regardless of how many accounts / currencies, I have available, Balance's window appears at a constant height. If I don't have enough 'cards' to fill the space, then the window's background colour appears – and it looks weird

![](https://user-images.githubusercontent.com/2099705/32145236-f537a912-bcbc-11e7-9e86-daff03a3e9b0.png)

The expected behaviour for me would be for the window height to adjust to account for the number of currencies/accounts that's available.

I think the current height it displays as would make a good max height before scrolling is enforced.

**Comment by einsteinx2** [comment]
It's supposed to automatically resize smaller... However it would also be great to support manual resizing, though I looked into doing that a while back and ran into issues with our popover library. Will need to look into this again. Moving to 1.1 (though we'll likely fix the auto-height sizing for 1.0).

**Comment by einsteinx2** [comment]
I fixed some resizing bugs, this should no longer be a problem. Leaving this open until I can confirm though.

**Comment by einsteinx2** [comment]
Confirmed this is fixed, especially with my latest other fix for add/hide accounts.
