### ISSUE TITLE
Crash when tapping Account name in Touch Bar

### ISSUE THREAD

**Issue by cjdowner** [balancemymoney/balance-open#206]
Reproducible crash. On the MacBook Pro with TouchBar, tapping any of the account names will instantly crash the app. Hangover from 'old Balance'.

[BalanceOpen_2017-10-29-153235_Christophers-MacBook-Pro.crash.zip](https://github.com/balancemymoney/balance-open/files/1425233/BalanceOpen_2017-10-29-153235_Christophers-MacBook-Pro.crash.zip)

**Comment by einsteinx2** [comment]
Whoops, touch bar for accounts and transactions tabs were supposed to be disabled until we re-implemented transaction searching.
