### ISSUE TITLE
Increase value text area in account headers to support larger values

### ISSUE THREAD

**Issue by cjdowner** [balancemymoney/balance-open#208]
Minor design issue:

When viewing an account, the width of the text area can be increased in the the headers, to account for larger values. Illustrated here by changing the currency to BTC.

![test](https://user-images.githubusercontent.com/2099705/32145500-9aa93d26-bcc1-11e7-9cf4-7f2dd7ea0eb8.gif)

Increasing the size of the area the text appears can help ensure everything will appear on one line as beautifully designed.

**Comment by einsteinx2** [comment]
Another good catch! The width should be set to the leading edge of the logo with some minor spacing.
