### ISSUE TITLE
Placeholder view required when there's no accounts or transactions

### ISSUE THREAD

**Issue by cjdowner** [balancemymoney/balance-open#209]
In cases where there are no transactions for accounts - we should show some text (and possibly) an icon just as a friendly way to say there's nothing to be displayed.

Right now, it's big and blank and I don't know if it's a bug or not!

**Comment by einsteinx2** [comment]
Great idea! We'll whip something up with Christian this week.

**Comment by einsteinx2** [comment]
We'll likely go with something similar to iOS, basically an add account button
