### ISSUE TITLE
Crash on control-Click > Find Similar Transactions

### ISSUE THREAD

**Issue by cjdowner** [balancemymoney/balance-open#210]
Found another reproducible crasher

When viewing your transactions, you can control-click any of these to reveal the shortcut menu. The top item is `Find Similar Transactions`. Out of curiousity, I clicked this and the app crashed.

[BalanceOpen_2017-10-29-160809_Bamako.crash.zip](https://github.com/balancemymoney/balance-open/files/1425277/BalanceOpen_2017-10-29-160809_Bamako.crash.zip)

**Comment by einsteinx2** [comment]
This was meant to be removed until we have searching re-enabled.

**Comment by cjdowner** [comment]
I just triggered this again. (0.9.8 debug) Going to reopen, sorry.

**Comment by einsteinx2** [comment]
Wow not sure how this made it back in. Moving to this sprint.
