### ISSUE TITLE
Copy Amount in the Transactions view copies amount in the wrong currency

### ISSUE THREAD

**Issue by cjdowner** [balancemymoney/balance-open#211]
In the Transactions view, I'm looking at some transactions which occurred on Coinbase.

In one transaction I received `0.00889991` BTC. When I right-click that, and choose 'Copy Amount', the amount in my clipboard is actually `$8,899.91`.

This amount also appears at the end of the transaction address when I 'Copy Transaction'

**Comment by einsteinx2** [comment]
Good catch!
