### ISSUE TITLE
Fix sqlcipher build script to build separate macOS and iOS libraries

### ISSUE THREAD

**Issue by einsteinx2** [balancemymoney/balance-open#229]
`URGENT: building for iOS simulator, but linking in object file (/Users/bbaron/workspacex/balance-open/Balance/Shared/Frameworks/libsqlcipher.a(sqlite3.o)) built for OSX. Note: This will be an error in the future.`

The problem is that the i386 and x86_64 libraries are targeting macOS instead of iOS, so we need separate binaries for macOS and iOS.

**Comment by wolffan** [comment]
➤ Ben Baron commented:

test

**Comment by wolffan** [comment]
➤ Ben Baron commented:

Figured I could fix this real quick but ran into configure issues trying to build for iOS with x86_64 architecture. Also from some searching, it turns out this "urgent" warning has been around for a few years now already. So yeah, it's not urgent.
