### ISSUE TITLE
Coinbase balances not updating

### ISSUE THREAD

**Issue by kristinatauch** [balancemymoney/balance-open#231]
**Is this a feature request or bug report? (please add a label and remove question)**

bug

**What is the current behavior?**

Coinbase balances not updating. Got some more ETH 3 hours ago on Coinbase and it's still not updated on Balance.

**If the current behavior is a bug, please provide the steps to reproduce starting from "launch Balance". If possible, please include a screenshot or a video.**

When I open Balance, the amount is not the same as on Coinbase.

**What is the expected behavior?**

To show the same balance. :)

**Which version of Balance is affected by this issue? Did this work in previous versions of Balance?**

**Comment by wolffan** [comment]
maybe was a problem on coinbase end but after getting keys things show on proper balance
