### ISSUE TITLE
Move feedback email sending to new backend

### ISSUE THREAD

**Issue by wolffan** [balancemymoney/balance-open#243]
Service: Mailgun

**Comment by wolffan** [comment]
➤ Raimon Lapuente commented:

review @benbaron7

**Comment by einsteinx2** [comment]
Email send functionality is done. Manually tested (need to figure out how to best unit test this, I guess using mock responses).

Still need to add the send feedback handler and write tests, then this is done.

**Comment by einsteinx2** [comment]
Added unit tests. Just need the handler now.

**Comment by einsteinx2** [comment]
Handler is done and client app updated. Merge requests submitted.
