### ISSUE TITLE
finish skinning Accounts tab

### ISSUE THREAD

**Issue by wolffan** [balancemymoney/balance-open#247]

**Comment by einsteinx2** [comment]
1. Remove elasticity from the cards
2. Remove border/shadow from cards
3. General behavior stays the same (i.e. cards scroll past the top like a regular scroll view), see framer for exact behavior: https://framer.cloud/VJOGT
4. Make sure accounts view is using PaintCodeView for logos, they should be same size as macOS logos

**Comment by einsteinx2** [comment]
Latest design spec (this plus the framer link):
![uploads/77047ad0-7f27-4c9c-a2ae-45008c4fc80c/26827943_187365308666202_1125855087_o.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F77047ad0-7f27-4c9c-a2ae-45008c4fc80c%2F26827943_187365308666202_1125855087_o.png)
