### ISSUE TITLE
add reconnect UI (similar to macOS ticket #157)

### ISSUE THREAD

**Issue by wolffan** [balancemymoney/balance-open#250]
┆Attachments: <a href="https:&#x2F;&#x2F;trello-attachments.s3.amazonaws.com&#x2F;59fc3a145f5fd3aa7230e0a3&#x2F;5a00859d933ade57cdb5e86f&#x2F;94bd76bf15c077fafffb0ce322f1eb23&#x2F;Simulator_Screen_Shot_-_iPhone_X_-_2017-11-09_at_11.18.31.png">Simulator Screen Shot - iPhone X - 2017-11-09 at 11.18.31.png</a>

**Comment by wolffan** [comment]
@einsteinx2 is this mandatory?

**Comment by einsteinx2** [comment]
Yes 100% mandatory for launch. We need to ensure this users never see non-updating balances with no message. I'll review this implementation and make sure it works as we need.

**Comment by einsteinx2** [comment]
reverse-dupe :P
