### ISSUE TITLE
Move servers to europe for legal purposes

### ISSUE THREAD

**Issue by wolffan** [balancemymoney/balance-open#255]

**Comment by wolffan** [comment]
➤ Ben Baron commented:

Looks like GAE doesn't support migrating to new regions so I'll have to create a new project there and push to it. Will require some downtime, which isn't a bit issue since we're in beta and only affects coinbase accounts anyway. When we get ready to push the profile code, we can push it to the new location.

**Comment by einsteinx2** [comment]
Created new project called balance-server-eur in the europe-west region. Deploying the server there now. Will change the server URL in the app to point to the new server and make a PR then this is all done. I'll make a new ticket for 1.0.1 to migrate historical pricing data from the US region.

**Comment by einsteinx2** [comment]
New server up and running, mysql setup, cron jobs running.
