### ISSUE TITLE
Ripple (XRP) tokens not showing in Balance

### ISSUE THREAD

**Issue by wolffan** [balancemymoney/balance-open#262]

**Comment by einsteinx2** [comment]
Appears to be working after merging in latest Kraken fixes. Of course as I try to confirm by re-adding my account, Kraken is down lol. When I confirm, I'll close.

**Comment by wolffan** [comment]
➤ Raimon Lapuente commented:

@benbaron7 remember

**Comment by wolffan** [comment]
➤ Ben Baron commented:

Yep re-added and I'm still seeing them. Must have been fixed from Raimon's Kraken fixes
