### ISSUE TITLE
Remove HockeyApp after Countly integration

### ISSUE THREAD

**Issue by wolffan** [balancemymoney/balance-open#282]
# Prerequisite
Replace hockeyapp with countly for logs

https://www.hockeyapp.net/help/sdk/ios/5.0.0/installation--setup.html

**Comment by einsteinx2** [comment]
Honestly I think we should just use Countly for crash logging as well. Let's see how their interface is, but unless it's terrible I'd rather not have to have 2 libraries included.

**Comment by wolffan** [comment]
I think it doesn't see my comments

**Comment by einsteinx2** [comment]
Looks like it does. We can remove hockeyapp, changed title.
