### ISSUE TITLE
GDAX balances incorrect (possibly due to held funds?)

### ISSUE THREAD

**Issue by rxl881** [balancemymoney/balance-open#290]
**What is the current behavior?**

Balances of linked GDAX account are displayed incorrectly.

![gdax](https://user-images.githubusercontent.com/6763606/32783822-f413200e-c944-11e7-8aa8-519d22c5f76f.png)

As shown in the screenshot the balances for bitcoin and Litecoin for the linked GDAX account are incorrect - negative value and different from the actual values held. 

For the Bitcoin value I believe that this is due to the subtraction of held funds (0.02907BTC shown held in the attached screenshot). If I cancel the order the Bitcoin value is displayed correctly.

However, I think that there is something else going on for the incorrect Litecoin balance, as there are no held funds on GDAX. In this instance the Litecoin coin holding should be being displayed as 1.01227678.

**What is the expected behavior?**

Display correct balances / coin holdings.

**Which version of Balance is affected by this issue? Did this work in previous versions of Balance?**

0.9.7 (latest, packaged build) displays this behaviour. I have not been able to test on other versions.

**Comment by einsteinx2** [comment]
Thanks for the bug report! There's definitely something wrong with the GDAX parsing, as @ricburton's account shows negative GBP as well. We'll try and get a fix into the next beta.

**Comment by wolffan** [comment]
@einsteinx2 this was due to another bug we fixed (negative values) can we close?

**Comment by einsteinx2** [comment]
Yep if that's fixed then this is done.
