### ISSUE TITLE
Unchecked assets in metamask wallet keep returning

### ISSUE THREAD

**Issue by ricburton** [balancemymoney/balance-open#296]
Bug Report

**What is the current behavior?**
The assets that I am unchecking from the list in settings are not staying unchecked.

**If the current behavior is a bug, please provide the steps to reproduce starting from "launch Balance". If possible, please include a screenshot or a video.**
Open settings. Uncheck some assets you don’t want to see. Wait a few seconds or minutes. See the assets pop back.

**What is the expected behavior?**
Stay unchecked.

**Which version of Balance is affected by this issue? Did this work in previous versions of Balance?**
0.9.7

**Comment by einsteinx2** [comment]
Thanks didn't realize this affected Ethplorer too, thought it was only Poloniex. Either way we have an open issue for the core problem: https://github.com/balancemymoney/balance-open/issues/107
