### ISSUE TITLE
Exchange rates file created in Documents folder

### ISSUE THREAD

**Issue by tbnv** [balancemymoney/balance-open#311]
The app creates a file called `currentExchangeRates.data` located in `~/Documents`. When the file is deleted and the app relaunched, the file is recreated.

I find it quite annoying (and I hope I'm not the only one 🤓) when my Documents show files that would be better out of sight.

**Comment by tbnv** [comment]
Sorry, can't add a label.

**Comment by einsteinx2** [comment]
Thanks for the report, that's definitely not the correct place! It was meant to be placed in the app documents area which is in the user Library and not visible. We'll get that fixed asap.

**Comment by einsteinx2** [comment]
Fixed!

**Comment by tbnv** [comment]
Great thanks.
