### ISSUE TITLE
Bitfinex transactions wrong order

### ISSUE THREAD

**Issue by wolffan** [balancemymoney/balance-open#314]
**What is the current behaviour?**

**What is the expected behavior?**
Transactions ordered by date

![uploads/4264e9b1-872b-4908-ba48-b89625f0b44c/Screen Shot 2017-11-29 at 18.55.44.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F4264e9b1-872b-4908-ba48-b89625f0b44c%2FScreen+Shot+2017-11-29+at+18.55.44.png)

**Comment by einsteinx2** [comment]
LOL wow

**Comment by wolffan** [comment]
Turns out the api was returning miliesconds not seconds ugh...

Fixed, problem is that if you already had old bitfinex transactions they will stay there (basically because they are set in the far future). Only solution to this is remove and add bitfinex again


![uploads/b11243ab-6bd6-4548-bd0a-b7382c93c2f9/Screen Shot 2017-12-02 at 22.12.45.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb11243ab-6bd6-4548-bd0a-b7382c93c2f9%2FScreen+Shot+2017-12-02+at+22.12.45.png)
