### ISSUE TITLE
Bitfinex not showing accounts even after restarting

### ISSUE THREAD

**Issue by einsteinx2** [balancemymoney/balance-open#315]
Probably same bug as the other exchanges before

**Comment by einsteinx2** [comment]
Actually this could be because I have no balances in Bitfinex, so maybe not a bug. But we should confirm.

**Comment by einsteinx2** [comment]
Ok now I just added Coinbase and it doesn't show any accounts either. I think this could be more keychain shenanigans...

**Comment by einsteinx2** [comment]
I'll debug this tomorrow

**Comment by einsteinx2** [comment]
Whoops spoke too soon, after the first sync the accounts showed up. So they're not showing on first add I guess (even though they definitely used to...). I'll make a new issue for that.

**Comment by wolffan** [comment]
@einsteinx2 it also shows to me on first addition not even need to wait to first sync...

**Comment by einsteinx2** [comment]
Yeah I think it's just that Bitfinex returns nothing when you have no balances.
