### ISSUE TITLE
Coinbase not showing accounts until first sync

### ISSUE THREAD

**Issue by einsteinx2** [balancemymoney/balance-open#316]

**Comment by wolffan** [comment]
@einsteinx2 is this still happening? I mean I fixed it for other exchanges but didn't remember happening on coinbase...

**Comment by wolffan** [comment]
@einsteinx2 I'm unable to reproduce. Even after removing the account, closing the app and relaunching, coinbase shows straight away...

**Comment by einsteinx2** [comment]
Ok probably bad old beta data on my machine or some other weirdness.
