### ISSUE TITLE
IOTA (Bitfinex and price ticker) missing dollar value

### ISSUE THREAD

**Issue by christianbaroni** [balancemymoney/balance-open#331]
Has a price on Bitfinex but nothing is shown in Balance. Also, its symbol should be IOTA rather than IOT.

<img width="394" alt="screen shot 2017-12-05 at 6 33 01 pm" src="https://user-images.githubusercontent.com/7061887/33636819-dbcc5b70-d9eb-11e7-9019-bc17a416c965.png">

**Comment by einsteinx2** [comment]
Adding the prices to the backend now. It's showing IOT because that's what Bitfinex returns. I'll add a special case for it in the client app.

**Comment by einsteinx2** [comment]
Pushed the backend and merged in the client change.

**Comment by christianbaroni** [comment]
Just cleaned and pulled the latest. Seeing the updated name but still no dollar value.

Also, according to: https://coinmarketcap.com/currencies/iota/ the currency name is IOTA, but its symbol is MIOTA.
