### ISSUE TITLE
Finish skinning add account view

### ISSUE THREAD

**Issue by ricburton** [balancemymoney/balance-open#334]
![screen shot 2017-12-07 at 12 24 53](https://user-images.githubusercontent.com/438160/33715280-e7aa00c8-db49-11e7-995a-bce66d1c45cf.png)

**Comment by einsteinx2** [comment]
Christian is redesigning this whole screen.

**Comment by einsteinx2** [comment]
I have this completed in the task/skin-add-accounts branch. Just need to do some polish on it with Christian tomorrow.
