### ISSUE TITLE
Height issue on prices tab on macOS Sierra

### ISSUE THREAD

**Issue by ricburton** [balancemymoney/balance-open#336]
Bug

**What is the current behaviour?**
When opening the app at the price tab section, the height is incorrect.

**If the current behavior is a bug, please provide the steps to reproduce starting from "launch Balance". If possible, please include a screenshot or a video.**

Open the app, go to prices tab, close the app, re-open it.

![screen shot 2017-12-07 at 12 32 13](https://user-images.githubusercontent.com/438160/33715584-fee17e14-db4a-11e7-978c-f1d51724d08b.png)

**What is the expected behavior?**

The height should be higher.

**Which version of Balance is affected by this issue? Did this work in previous versions of Balance?**
0.9.8

**Comment by einsteinx2** [comment]
I can't reproduce this. Is there any other information you can provide? For example how many accounts do you have connected? Does it always happen?

**Comment by ricburton** [comment]
Lots of accounts connected.
Sierra

**Comment by einsteinx2** [comment]
Seeing this on High Sierra as well now somehow. Prices tab seems to use the last tab's height.
