### ISSUE TITLE
Coinbase shows 0.00 USD after adding to Balance iOS app

### ISSUE THREAD

**Issue by kristinatauch** [balancemymoney/balance-open#337]
**Is this a feature request or bug report?** (if it's a bug, please add a label and remove question, if it's a feature request, please head to https://trello.com/b/Hbg05zQO/feature-request and create or upvote an existing feature requwest)  

BUG

**What is the current behaviour?**

After adding Coinbase to Balance iOS app it is showing I have 0.00 USD.

**If the current behavior is a bug, please provide the steps to reproduce starting from "launch Balance". If possible, please include a screenshot or a video.**

Downloaded the app, connected to Coinbase, after it got authorised only the bar with Coinbase logo showed up with 0.00 UDS balance

**What is the expected behavior?**

That the actual Coinbase balance shows up

**Which version of Balance is affected by this issue? Did this work in previous versions of Balance?**

iOS app, it worked when I connected it before but it wasn't showing the correct balances so I've deleted the app and reinstalled 

![coinbase error](https://user-images.githubusercontent.com/30265438/33715622-162b207a-db4b-11e7-8998-1472f0966ac5.jpg)

**Comment by einsteinx2** [comment]
There is a very large chance that Coinbase was having issues. It's been going down constantly recently. 

However we should be handling these types of problems better. Placing in 1.0.1 as this is not trivial to handle properly.

**Comment by einsteinx2** [comment]
This is no longer reproducible
