### ISSUE TITLE
iOS app is showing very different converted amounts than the mac app even though they should be using the same convert function.

### ISSUE THREAD

**Issue by einsteinx2** [balancemymoney/balance-open#338]
In my case iOS showing lower converted prices than the Mac app. Need to confirm how the iOS app is getting those numbers.

**Comment by wolffan** [comment]
let's not merge stuff until it's on review....

**Comment by einsteinx2** [comment]
As mentioned this morning, I'd really prefer that we only make merge requests when we are...requesting a merge haha. Makes it much clearer and then I can just run through all PRs without worrying about which ones are actual requests and which ones are not.
