### ISSUE TITLE
On iOS, write a one time run function to rewrite all keychain items with the new permissions

### ISSUE THREAD

**Issue by einsteinx2** [balancemymoney/balance-open#344]

**Comment by Rolvar** [comment]
could you give me a better explanation of this feature/bug?

**Comment by wolffan** [comment]
just read and write all the keychain entries. (the new code already changes the permissions and stores in a different way).
you can iterate the dictionary of keychains.
Go through each institution, read it and store it's values again

**Comment by Rolvar** [comment]
origin/feature/344-rewrite-all-keychain-items

**Comment by einsteinx2** [comment]
Actually going to skip this. Any affected users can reinstall the app, it's a small set of early beta users.
