### ISSUE TITLE
Launch at log in preference does not write to Login Items

### ISSUE THREAD

**Issue by cjdowner** [balancemymoney/balance-open#352]
**Summary**
When you select the `Launch at log in` preference, Balance doesn't do anything. This is because nothing is being written to the System's `Login Items` preference.

The expected behaviour is that selecting this preference, will add – then toggle the option found here, in System Preferences > Users & Groups > Login Items.

<img width="670" alt="screen shot 2017-12-13 at 17 28 54" src="https://user-images.githubusercontent.com/2099705/33953031-881afbb2-e02b-11e7-853b-92dff7785c08.png">

This is something that can be toggled manually, but it defeats the purpose of having the preference.

**Notes**
macOS 10.13.2, BalanceOpen 0.9.8 (debug)

**Comment by ricburton** [comment]
I also just had this problem.

**Comment by einsteinx2** [comment]
It's not supposed to. That is a deprecated method of creating login items that is fully unsupported now when compiling with High Sierra SDK. Unfortunately this is just another case of Apple being stupid, and we can't do anything about it. We're doing it the correct way, which unfortunately does not place an item here.

**Comment by einsteinx2** [comment]
I looked into this when fixing the launch at login option in the app.
