### ISSUE TITLE
Custom Balance shortcut is not respected

### ISSUE THREAD

**Issue by cjdowner** [balancemymoney/balance-open#353]
**Summary**
Unable to edit / add a custom shortcut to hide/show Balance.

**Steps to reproduce**
Open Balance preferences, and click to add a new shortcut. `Control-B` works well (not used by anything).

**Expected results**
For the entered shortcut to be saved, and for you to be able to use it anywhere in the Desktop to show Balance's Window

**Actual results**
After you enter the shortcut, pressing it will hide-show Balance. However, if you click on a different Preference tab, or you close the Preference window the shortcut will swap back to its default `Control-Option-Command-B` combo.

**Notes**
macOS 10.13.2, BalanceOpen 0.9.8 (debug)

**Comment by einsteinx2** [comment]
Good find!
