### ISSUE TITLE
Fix default button color

### ISSUE THREAD

**Issue by cjdowner** [balancemymoney/balance-open#354]
Design issue:

On certain screens, Balance shows a button - such as password confrim, and back to your accounts overview.

This is black, and the Balance UI is now white. This is leftovers from previous Balance which was using a darker interface.

I think standard `NSButton` could be a quick fix here until all UI elements are reviewed / redesigned.

<img width="420" alt="screen shot 2017-12-13 at 17 48 08" src="https://user-images.githubusercontent.com/2099705/33953782-2876c35a-e02e-11e7-8efe-915b8404437c.png">

<img width="409" alt="screen shot 2017-12-13 at 17 49 26" src="https://user-images.githubusercontent.com/2099705/33953785-2ad6a980-e02e-11e7-98db-c101c7f2eadc.png">

**Comment by einsteinx2** [comment]
Will forward this to Christian, as he may prefer to just make another custom button. In fact we may already have a light button to use.

**Comment by einsteinx2** [comment]
Per Christian, replace with stock NSButtons styled like the Enable button in Prefs > Security

**Comment by einsteinx2** [comment]
Ironically this is one thing we _weren't_ custom drawing lol. The system is "helpfully" changing the button style because you have dark mode turned on. We need to override it to always be light mode since we use one style now.
