### ISSUE TITLE
Instant Open

### ISSUE THREAD

**Issue by ricburton** [balancemymoney/balance-open#355]
The popover opens with an animation but this can be frustrating when you’re checking the app repeatedly.

Instant open would be great.

**Comment by ricburton** [comment]
I am on 0.9.11. Should this be live in that version?

**Comment by einsteinx2** [comment]
Not sure but it's definitely live in the latest version.

**Comment by ricburton** [comment]
Ah I see the issue here. I don't want the animation to be there even after entering the password / using Touch ID. Just BAM.

Sent via Superhuman ( https://sprh.mn/?vip=richard@balancemy.money )
