### ISSUE TITLE
Prices tab Issues

### ISSUE THREAD

**Issue by cjdowner** [balancemymoney/balance-open#356]
I can create individual issues for each of these, but I've a feeling that you could possibly kill many bids with one stone.

1. **Values are not in sync with https://coinmarketcap.com**

I presume this is your data source, but there's several issues here including coins not being ordered by market cap correctly in Balance, and there being some delay between the values

<img width="824" alt="screen shot 2017-12-13 at 18 04 18" src="https://user-images.githubusercontent.com/2099705/33954431-33bb713c-e030-11e7-949f-1e0858dea0ab.png">

2. **MIOTA value is at $0.00**

As seen above. This is incorrect, but I'm pointing this out specifically as it's got a high market cap, and it's wrong.

3. **Design special case when currency value is below $0.01**

I think Balance is doing the right thing by only showing two decimal places when showing a currency value, as anything beyond that for fiat values is irrelevant. However, there are some tokens which don't even make that. Bytecoin for example's value is `$0.002633` at time of writing.

To display `$0.00` (which Balance does currently) would be wrong, but you also don't want to mess up the flow by showing extra integers. Just displaying `>$0.00` would be accurate without being specific

4. **Currency names aren't filled**

You can see in the above screenshot that Balance names "BTC" as Bitcoin, etc but only to some extent. As you scroll down, you can see that the currency name matches the ticker value - which is pretty useless and can be improved.

5. **SBD**

This is kind of hilarious. As you scroll down the list you'll see a currency has a name!

<img width="420" alt="screen shot 2017-12-13 at 18 11 57" src="https://user-images.githubusercontent.com/2099705/33954800-68c27eec-e031-11e7-969a-02373a1e52c3.png">

I got pretty excited and thought the Solomon Islands decentralised their currency and missed the news, but alas. That's actually the ticker code for "Steem Dollars". 

I had never seen a conflict with a fiat currency before, but there's one. Well done on the data source for trying to populate it, but it's kinda wrong. :)

**Comment by einsteinx2** [comment]
Thanks for all the feedback! We discussed this in chat but for the record:

1. We will always have different prices than coinmarketcap as they do their own averaging that is frequently incorrect, especially during big rises and drops. We may use them to fill in gaps of currencies we don't have prices for, and possibly just to get market cap and other info, but we're not going to use their prices as we can be more accurate doing our own averaging.

2. Yep, we have an open issue for this one: IOTA (Bitfinex) missing dollar value
#331

3. Christian and I actually just talked about this the other day, but I forgot to create an issue. I've created this one now: #360

4. This is something that was on my list to do but forgot to make an issue for it. This will likely need to wait til a 1.0.x release as we'll need to pull the names from somewhere which will take some infrastructure. There are too many to manually add them all to the Currency enum so I had only added the most common ones. I've created this issue in 1.0.1 milestone: #361

5. Haha that's pretty funny. I'll just remove that fiat currency as it's extremely unlikely to be used. I've created this issue in the 1.0 milestone: #362
