### ISSUE TITLE
Design needed for login / connect to exchange screen

### ISSUE THREAD

**Issue by cjdowner** [balancemymoney/balance-open#357]
With the new design language, and mockups for all the main views being implemented, I think there's an important one which has been forgotten:

<img width="412" alt="screen shot 2017-12-13 at 18 19 18" src="https://user-images.githubusercontent.com/2099705/33955081-41de43aa-e032-11e7-8b7b-4a9f8c88d3e1.png">

I think this could be re-designed with the new style guide in mind, but be flexible enough to deal with the various fields and stuff different exchanges require. It would be extra nice if this perhaps incorporated some of the exchanges' branding.

**Comment by einsteinx2** [comment]
Christian is working on this now, we have an open ticket for it here: Finish skinning add account view
#334
