### ISSUE TITLE
Improve copy for remove account confirmation

### ISSUE THREAD

**Issue by cjdowner** [balancemymoney/balance-open#358]
This might seem small, but I think it would be a worthwhile enhancement. There's a bit of an art to writing good UX copy.

<img width="501" alt="screen shot 2017-12-13 at 17 45 51" src="https://user-images.githubusercontent.com/2099705/33955416-616546be-e033-11e7-8e8f-d31bf57831d0.png">

Suggestion

>**Are you sure you want to remove “`Poloniex`”?**
>Removing this account will hide its tokens and transactions from Balance. Do you want to continue?
><kbd>Cancel</kbd> <kbd>Remove Account</kbd>

few reasons: We confirm the account name they're removing, and we tell them the consequences.

**Comment by einsteinx2** [comment]
Great idea

**Comment by einsteinx2** [comment]
Also noticed for some reason I can't click on any accounts on the left side... Fixing that now as well.

**Comment by einsteinx2** [comment]
huh weird... I first opened prefs and couldn't click on any of them (but I could click the check boxes to hide a token). Typed that reply above, clicked back to Balance and it worked...

**Comment by einsteinx2** [comment]
Weird can't reproduce now. I'll just fix the copy for now, no use chasing ghosts.

**Comment by einsteinx2** [comment]
Ended up going with this copy, but we can tweak it later.


![uploads/37b5da0c-58fe-42c0-9d7f-8181f765403c/Screen Shot 2017-12-21 at 9.15.17 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F37b5da0c-58fe-42c0-9d7f-8181f765403c%2FScreen+Shot+2017-12-21+at+9.15.17+PM.png)
