### ISSUE TITLE
Add automated monitoring of at least /hello and /exchangeRates endpoints

### ISSUE THREAD

**Issue by einsteinx2** [balancemymoney/balance-open#369]
Today the server was not responding due to an unknown problem. I was able to fix it in about 5 min once I found out, but I only found out because Raimon noticed it wasn't working (he had assumed I shut it down after making the europe instance). We need to have automated monitoring in place to catch these and notify us ASAP so we can fix.

If we call /hello and /exchangeRates every minute, check for "hello" response and very that we get valid json back for exchangeRates, then we should be good. The former verifies the server is up at all, and the latter verifies the db is working.

**Comment by einsteinx2** [comment]
Raimon recommended DataDog: https://docs.datadoghq.com/integrations/google_app_engine/

**Comment by wolffan** [comment]
Created two monitors for both endpoints :)
Invited @einsteinx2 to datadog so he can be notified when something goes wrong
