### ISSUE TITLE
Renaming Ethplorer to Ethereum Address

### ISSUE THREAD

**Issue by ricburton** [balancemymoney/balance-open#371]
I think it might be a little clearer to name this option as an Ethereum address.

**Comment by wolffan** [comment]
This is actually an issue on iOS, on mac the address text is "Add Wallet Address" which probably should be replaced to "Ethereum Address" or "ERC-20 Address" since we don't suport bitcoin

**Comment by wolffan** [comment]
@christianbaroni I think the add account buttons are done by you right? Could you update the Add Wallet as explained above?
