### ISSUE TITLE
Bitfinex stores credentials globally (not possible to add 2 accounts)

### ISSUE THREAD

**Issue by einsteinx2** [balancemymoney/balance-open#380]
Look in the authenticationChallenge method. This is incorrect. Everything should be saved per institution.

**Comment by einsteinx2** [comment]
Same issue for GDAX.

It looks like for 1.0 we can fix this by just using unique credentials identifiers instead of main I think.

**Comment by einsteinx2** [comment]
Looks like Kraken is the same...

**Comment by joeblau** [comment]
Should the internal credentials variable be an array or credentials?

**Comment by einsteinx2** [comment]
@joeblau It should be Credentials as it is, the problem is in the creation of new institutions, it's using the same credentials key for all Bitfinex accounts, and then another one for all Kraken, etc. So if you add 2 Bitfinex accounts, it'll overwrite the credentials of the other one. 

We actually will be refactoring all of the API code for 1.0.x as they were written by different people and need to be standardized. Also in 1.1, this stuff will all be stored in the new secure keystore we're working on, so that will change things a bit as well.

**Comment by einsteinx2** [comment]
This is a bit of an edge case, as it's unlikely to have more than one account at an institution. Bumping to 1.0.1.

**Comment by joeblau** [comment]
Ah okay.  I'm trying to see if there is any place I can help out.
