### ISSUE TITLE
Server in Europe is down

### ISSUE THREAD

**Issue by wolffan** [balancemymoney/balance-open#389]
**What is the current behavior?**
Server returns error 4

// 20171218105921
// https://balance-server-eur.appspot.com/exchangeRates

{
  "code": 4,
  "message": ""
}

**What is the expected behavior?**
We should get a list of exchange rates

**Which version of Balance is affected by this issue? Did this work in previous versions of Balance?**
Server

**Comment by einsteinx2** [comment]
This is fixed now. Forgot to manually run a cron job when I set it up, will not be a problem in the future since it will run each week.
