### ISSUE TITLE
Improve Look of View when Scrollbar preferences is set to Always on

### ISSUE THREAD

**Issue by cjdowner** [balancemymoney/balance-open#39]
**Summary:**

When the macOS preference for scrollbars is set to 'Always', improve the look for the window

**Steps to Reproduce:**
Go to `System Preferences > General` and set the scrollbar preference to Always
<img width="438" alt="screen shot 2017-06-17 at 09 46 20" src="https://user-images.githubusercontent.com/2099705/27251614-9d0a01a6-5342-11e7-9bcc-70a06afeb7cb.png">
Launch Balance and have at least two currencies visible.

**Actual Results:**
The width of the window increases to accommodate the scrollbar gutter. Due to the colour of the cells, this is somewhat noticeable.
![screen shot 2017-06-17 at 09 45 32](https://user-images.githubusercontent.com/2099705/27251591-1774ecf4-5342-11e7-9e4b-6ef974e1e0fc.png)

**Expected Results:**
This is a tricky one... It wouldn't be worth creating a custom scrollview where you could implement your own scrollbar ultimately. Perhaps the colour of the cells could change to have less of a contrast

**Notes:**
On the whole, it's low priority. I'm filing this because I have the scrollbar preference on to catch out edge cases like this 😎

**Comment by ricburton** [comment]
Thank you!
Spark by Readdle

**Comment by einsteinx2** [comment]
This is fixed finally!
