### ISSUE TITLE
Decrease minimum window height

### ISSUE THREAD

**Issue by cjdowner** [balancemymoney/balance-open#40]
**Summary:**
When you have only one currency visible, Balance looks a bit wacky.

**Steps to Reproduce:**
Open preferences, go to Accounts, and show only one currency.
Return to the main view and observe

**Actual Results:**
![screen shot 2017-06-17 at 09 57 02](https://user-images.githubusercontent.com/2099705/27251674-89a56104-5343-11e7-84f2-921047c9f408.png)

**Expected Results:**
The minimum window height should be that to perfectly accommodate one cell.

**Notes:**
The minimum height seems to be fairly arbitrary right now. It's too short to perfectly accommodate two cells, and too tall for one!

**Comment by einsteinx2** [comment]
Yeah it's a bit arbitrary. Also we're missing the total balance bar which we need to add back, which will take up some space. In any case, we'll need to get the sizing right. Moving to 1.0 milestone.

**Comment by einsteinx2** [comment]
Closing this as it conflicts with App height is incorrect on a fresh open #104
