### ISSUE TITLE
High Sierra error on Sparkle

### ISSUE THREAD

**Issue by wolffan** [balancemymoney/balance-open#403]
**What is the current behavior?**
We get a popup with a Sparkle alert

**Which version of Balance is affected by this issue? Did this work in previous versions of Balance?**
Current after updating to High Sierra

![uploads/76309706-f24e-440c-a831-414395934cef/Screen Shot 2017-12-22 at 10.19.43.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F76309706-f24e-440c-a831-414395934cef%2FScreen+Shot+2017-12-22+at+10.19.43.png)

**Comment by einsteinx2** [comment]
Looks like a signing issue local to your machine. We don't need to DSA sign the updates though it could be nice.
