### ISSUE TITLE
Don't allow users to hide all accounts in an institution

### ISSUE THREAD

**Issue by cjdowner** [balancemymoney/balance-open#41]
**Summary:**
When you have deselected all currencies in the Preferences, Balance looks very empty. :( 

**Steps to Reproduce:**
Open Preferences, go to Accounts, and deselect everything!

**Actual Results:**
![screen shot 2017-06-17 at 10 00 06](https://user-images.githubusercontent.com/2099705/27251695-f16bd43a-5343-11e7-9c17-987b5a50a13d.png)

**Expected Results:**
Perhaps there could be some placeholder text or a button to tell you that you need to enable some currencies.

**Notes:**
Extreme edge case, but the details make the app.

**Comment by einsteinx2** [comment]
Rather than having a placeholder, I think we should just not allow users to hide all accounts, otherwise what is the point of them connecting to that institution?

**Comment by einsteinx2** [comment]
Fixed in highlander merge
