### ISSUE TITLE
Refactor Kraken API the same way as Bitfinex and GDAX

### ISSUE THREAD

**Issue by einsteinx2** [balancemymoney/balance-open#435]
They are currently down for maintenance so it's impossible to test. Leaving it alone for now, but it needs basically the same refactoring as the others.

**Comment by wolffan** [comment]
what's that for?

**Comment by einsteinx2** [comment]
For my sanity haha. It's just the same changes I made to the other APIs to make the code more compact and cleaner, I just couldn't test Kraken because they were down so I made a separate issue.
