### ISSUE TITLE
Show Currency Price

### ISSUE THREAD

**Issue by hexsprite** [balancemymoney/balance-open#44]
right now it shows the total value of holdings for a currency but not the current price of 1 unit of the currency itself which would be handy

**Comment by ricburton** [comment]
Love this idea ❤️

**Comment by einsteinx2** [comment]
Great idea

**Comment by averbs** [comment]
@ricburton it's here as well. 👍

**Comment by ricburton** [comment]
☺️

**Comment by einsteinx2** [comment]
Great idea, definitely in the pipeline for 1.0.

**Comment by einsteinx2** [comment]
Oh actually misread your initial post a bit... We're working on some kind of currency display to allow you to see the value of your holdings in the currency of your choosing, but may not have a price chart for 1.0. However, we're working on it.

**Comment by wolffan** [comment]
@einsteinx2 should we move to v 1.1?

**Comment by einsteinx2** [comment]
Yep, this is bumped to 1.1. 

@hexsprite we're still working on this, but we had to do a feature block for 1.0 as we're trying to release next week. However we'll continue to be actively working on the 1.0.1 and 1.1 tickets.

**Comment by einsteinx2** [comment]
Price ticker is actually making it in for 1.0. It will be a separate tab and will track all popular crypto currencies as well as many altcoins.

**Comment by einsteinx2** [comment]
Closing this ticket as it's almost done and will be in the next betas.
