### ISSUE TITLE
Prices not updating (error -999)

### ISSUE THREAD

**Issue by christianbaroni** [balancemymoney/balance-open#442]
Noticed prices weren’t updating for a brief period this morning. This was showing in the console:
![313aad05-d617-48ce-93fa-fad66873c30d](https://user-images.githubusercontent.com/7061887/34911119-06d39662-f891-11e7-8b55-18f1dbbdf78d.jpeg)

**Comment by christianbaroni** [comment]
Happening again today, been stuck for at least an hour.

**Comment by wolffan** [comment]
sorted by @einsteinx2 certificate issues
