### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by lfarah** [balancemymoney/balance-open#46]
The app is Awesome, but we need to work on the `README.md`.

First thing I tried to do was to run the command line, but that didn't work 😞 
Then I had to go to 3 different websites to try to install sqlcipher. I installed it, but no luck on getting that command line to work. Then I opened the ```BalanceOpen.xcodeproj``` and pressed the "Build and Run" button 🤘

We need a tutorial on the README page, teaching the user go from `git clone` to opening the app on the menu bar.
Besides installation, the `README.md` also lacks other information. I created a [README template](https://github.com/awesome-labs/iOS-readme-template) to help it out

**Comment by ricburton** [comment]
Amazing. Did you submit a pull request?

Also, we should link to the releases page from the README.

**Comment by einsteinx2** [comment]
It looks like @ricburton changed the readme text after I posted it. The original text said "sqlcipher compile command (only necessary to update it)" which is actually correct...

That command is NOT necessary to run, only when updating sqlcipher as my original readme text said. I had master commits unlocked for admins so I could push quickly, but this is why we have them on. I'm turning it back on now. That readme change should have been reviewed.

With that said, I'll update the readme now to reflect the actual steps which is literally: 1. clone, 2. build and run. That's it lol.

**Comment by einsteinx2** [comment]
Pull request with README fixes here that needs review: https://github.com/balancemymoney/balance-open/pull/48

**Comment by einsteinx2** [comment]
Merged
