### ISSUE TITLE
Coinbase account not showing in Balance after successful OAuth login

### ISSUE THREAD

**Issue by christianbaroni** [balancemymoney/balance-open#476]
A friend tried adding his Coinbase account to Balance and went through the OAuth process successfully. When redirected to Balance, his Coinbase account wasn't shown. He tried four times.

![img_0952](https://user-images.githubusercontent.com/7061887/35241323-16f57ef8-ff84-11e7-9f5f-12cbeef3b893.PNG)

**Comment by wolffan** [comment]
on mobile we currently have a bug where the main screen won't autorefresh. It needs to pull to refresh the UI.

There's another ticket but just FYI @christianbaroni

**Comment by wolffan** [comment]
Related #489

**Comment by wolffan** [comment]
I'm trying this. What happens is the user gets redirected to Ticker, not accounts... but the coinbase account does show

**Comment by wolffan** [comment]
This should be fixed now

**Comment by wolffan** [comment]
@christianbaroni  could you ask your friend to retry when @einsteinx2 makes a new build?
