### ISSUE TITLE
No `back` button on `add account` popover (macOS) at first launch

### ISSUE THREAD

**Issue by demianturner** [balancemymoney/balance-open#488]
label: bug

**What is the current behavior?**
bottom left corner of `add accounts` popover has link to Github instead of `back button`

**If the current behavior is a bug, please provide the steps to reproduce starting from "launch Balance". If possible, please include a screenshot or a video.**
![](https://i.imgur.com/O2Kgw20.png)

**What is the expected behavior?**
bottom left corner of `add accounts` popover should have `back button`.  You have to quit app in order to get back to main screen with 3 tabs.

**Which version of Balance is affected by this issue? Did this work in previous versions of Balance?**
latest

**Comment by einsteinx2** [comment]
Thanks for the bug report! Check out the 1.0-beta1 release we just posted. This issue is resolved.

**Comment by einsteinx2** [comment]
Oh wait actually I just noticed you have the Bittrex button, so you are on the new release, sorry. I thought this was fixed. Prioritizing for release.

**Comment by wolffan** [comment]
I can reproduce this one

**Comment by wolffan** [comment]
We had the github link.
I removed all the logic that show/hide for those buttons and made them align (always show)

![uploads/b2fb112f-ac49-47a0-b4c3-4de7b37aa860/Screen Shot 2018-01-25 at 10.21.55.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb2fb112f-ac49-47a0-b4c3-4de7b37aa860%2FScreen+Shot+2018-01-25+at+10.21.55.png)

**Comment by demianturner** [comment]
cool, I guess you can close this (or I will try), I saw the fix in #493 - thanks! Great app btw 👍
