### ISSUE TITLE
iOS app doesn't seem to auto-sync (pull to refresh works)

### ISSUE THREAD

**Issue by einsteinx2** [balancemymoney/balance-open#489]
Raimon wasn't seeing his numbers updating. I re-opened the app on my phone and it didn't seem to update either. I pulled from the top to refresh and it worked fine.

We need to check:
- Is auto-sync working when the app is in the foreground
- Is background refresh working

Syncing itself seems to work fine.

**Comment by wolffan** [comment]
Related: https://huboard.com/balancemymoney/balance-open#/issues/290594314

Won't autorefresh even:
- opening the app again after reinstall
- switching apps (like when you add coinbase)

**Comment by einsteinx2** [comment]
Actually looking into the code a bit and testing, auto-sync is implemented and working (it's entirely in the data model so the code is 100% the same for iOS and Mac, at least while the app is running). I watched via breakpoints, the following: 

Network becomes available, app syncs, it sends the sync completed notification, the accounts view listens for it, calls reloadData, and I see things update. This is pulled directly from develop without your changes... 

However I'm now also seeing the Coinbase password invalid bug, so everything is updating automatically except Coinbase for me, no need for any other changes other than fixing the Coinbase issue. So I'm not sure why we could have been seeing things not update unless we all had Coinbase as the top card and all had the password invalid issue, but I could have sworn we were seeing the other stuff not update as well... 

I'm pretty confused at the moment. Diving deeper.

**Comment by einsteinx2** [comment]
Also noticed that Transactions view doesn't even listen to the sync completed notification and it's refresh code calls sync instead of reloading it's data /facepalm

Fixing that now and double checking the price ticker as well.

**Comment by einsteinx2** [comment]
Actually, looks like the notification handling is implemented in the view model (opposite of the accounts view and how we do it in macOS). Fixing that now.

**Comment by einsteinx2** [comment]
There's also various other notifications it's not listening for. I'm going to essentially duplicate what we do in macOS

**Comment by einsteinx2** [comment]
I've added all the missing notifications and fixed all 3 tabs. Originally I was going to just reload local data when a user does a pull to refresh, but I realize that they'll expect that to perform a sync (even though that happens every minute anyway), so I'm re-adding that behavior.
