### ISSUE TITLE
weird crash in latest macOS (balance-v1.0-beta1)

### ISSUE THREAD

**Issue by demianturner** [balancemymoney/balance-open#506]
bug report

**What is the current behavior?**
crash when tabbing through the app

**If the current behavior is a bug, please provide the steps to reproduce starting from "launch Balance". If possible, please include a screenshot or a video.**

1. launch app
1. click to open status bar popover
1. tab 7 times (5 for controls on top of window, 6 not clear where it goes, 7 = instant crash)

![console 2 317 messages 2018-01-26 2 pm-29-58](https://user-images.githubusercontent.com/136587/35457160-fc1d1f76-02a5-11e8-83b2-ee3c10e26c6f.png)

**What is the expected behavior?**
crash-free

**Which version of Balance is affected by this issue? Did this work in previous versions of Balance?**
affected = balance-v1.0-beta1

**Comment by einsteinx2** [comment]
Thanks! We'll look into this ASAP.

**Comment by einsteinx2** [comment]
Moving to this sprint.

**Comment by einsteinx2** [comment]
Reproduced.

**Comment by einsteinx2** [comment]
Fixed. Tab key now cycles through the tabs.

**Comment by demianturner** [comment]
addressed in https://github.com/balancemymoney/balance-open/pull/560

**Comment by einsteinx2** [comment]
@demianturner since the PR is still in review, let's keep this open for now. We use Huboard for organization and closing the ticket removes it from the Review column.

**Comment by demianturner** [comment]
Sure, just trying to be helpful.  Huboard looks cool.
