### ISSUE TITLE
Add loading spinner in the Balance bar

### ISSUE THREAD

**Issue by einsteinx2** [balancemymoney/balance-open#508]
When the iOS app first opens it's hard to tell if it's syncing or when it finishes. We should have a loading spinner in the Balance bar in accounts while syncing is occurring. This already has Christian's approval.

**Comment by wolffan** [comment]
A solution that shows the spinner if we are loading is acceptable?

**Comment by wolffan** [comment]
lol, the syncer won't show because Sync UI is shown before the actual syncer starts. @einsteinx2 
I've left code that will show a syncing ui if we open the tab and we are syncing.
