### ISSUE TITLE
Prices view is inconsistent between apps

### ISSUE THREAD

**Issue by cjdowner** [balancemymoney/balance-open#513]
I don't know if this was a conscious design choice, or if one will end up looking like the other - but for 1.0 there's going to be some difference between these two views (difference of name has already been filed) 

Though Mac and iOS are different, as you're using a custom UI that suits both, I think improvements can be made.

You can see on the Mac, you have double text, with the coin code above in grey, with the name underneath.

<img width="404" alt="screen shot 2018-01-27 at 12 03 22" src="https://user-images.githubusercontent.com/2099705/35471789-6262d924-035a-11e8-93bb-14cee3423e6e.png">

On iOS, the format is `Coinname (CODE)`

<img width="375" src="https://user-images.githubusercontent.com/2099705/35471788-5fab5a44-035a-11e8-978a-528b4ccb2a0a.PNG">

Also note the difference between the titles (Popular, Portfolio, Other)

FWIW I prefer the look on the Mac. I'm not super wild over the pill shape and big padding. As a suggestion, perhaps "Popular", "Other" could be cards, rather than every cell.

**Comment by einsteinx2** [comment]
Yep this just isn't skinned yet.

**Comment by einsteinx2** [comment]
This is covered in the new design issues I opened.
