### ISSUE TITLE
Edit button required on Settings view

### ISSUE THREAD

**Issue by cjdowner** [balancemymoney/balance-open#519]
I wanted to remove all my accounts whilst testing, and was worried that it wasn't possible. I did discover that you could swipe right to left on the cell to reveal the delete button.

<img width="375" src="https://user-images.githubusercontent.com/2099705/35472025-6cd87e40-035f-11e8-9ecd-40f4ad8f16b5.PNG">

Whilst that's normal for lists, I do worry it's perhaps not _that_ discoverable. An edit button that you can tap to reveal the indicator buttons on the left side of the removable cells would be a lot more at home on iOS I feel.

**Comment by einsteinx2** [comment]
I definitely had the same discovery problem. Moving this to the next sprint.
