### ISSUE TITLE
Improve iOS design

### ISSUE THREAD

**Issue by wolffan** [balancemymoney/balance-open#525]
**What is the expected behavior?**
We want to rething and redo the iOS design.

**Which version of Balance is affected by this issue? Did this work in previous versions of Balance?**

**Comment by einsteinx2** [comment]
To help Christian, I'm going to create an iOS theme file.

**Comment by einsteinx2** [comment]
This is all in the branch task/525/ios-design

Theme file created, also I merged in the account loading spinner fix. All iOS final design work will be done in this branch and then should be merged in by Monday end of day.

**Comment by einsteinx2** [comment]
Closing this to open individual issues
