### ISSUE TITLE
Coinbase balances not updating

### ISSUE THREAD

**Issue by ricburton** [balancemymoney/balance-open#55]
**Problem**
The balance in Balance does not reflect the balance in Coinbase. This is likely due to the one-an-hour rolling of keys.

**Steps to recreate**
I am not sure of the best way to get the app to do this again because when I refresh my keys the balance will be updated. 

**Attachments**
My logs are attached:
[balance-open-not-updating-coinbase-logs.zip](https://shipusercontent.com/4b6931baa588969ad2d7f54f13cab66c/balance-open-not-updating-coinbase-logs.zip)

**Comment by wolffan** [comment]
Extra info, backend related: https://console.cloud.google.com/logs/viewer?project=bal-subscription-server&organizationId=803454611209&minLogLevel=0&expandAll=false&resource=gae_app&pli=1&filters=text%3ArefreshToken&timestamp=2017-07-11T14%3A50%3A43.535690000Z&advancedFilter=resource.type%3D%22gae_app%22%0Aresource.labels.module_id%3D%22default%22%0Aresource.labels.zone%3D%22us12%22%0Aresource.labels.project_id%3D%22bal-subscription-server%22%0Aresource.labels.version_id%3D%22102%22%0Atimestamp%3D%222017-07-10T17%3A03%3A31.563698000Z%22%0AinsertId%3D%225963b36400094f2fa6bddc10%22

**Comment by einsteinx2** [comment]
Raimon fixed this.

**Comment by kristinatauch** [comment]
Coinbase balances not updating. Reopening this issue.
