### ISSUE TITLE
[Idea] Support for Tokens

### ISSUE THREAD

**Issue by ricburton** [balancemymoney/balance-open#56]
Tokens powered by the Ethereum Request for Comment (ERC20) specification are becoming very popular.

I am increasingly concerned about the phishing attacks people are falling victim to at [MyEtherWallet.com](http://MyEtherWallet.com). It seems that lots of people are losing money when they are tricked into visiting websites that look similar to the open source, Chrome-based wallet.

I think people would be much less likely to fall for a phishing attack if they had to go to a separate application on their Mac to manage their tokens.

Here is the summary of my research into the area so far:

https://theethereum.wiki/w/index.php/ERC20_Wallet_Support
https://ethereum.stackexchange.com/questions/9054/are-there-ethereum-wallets-other-that-mist-that-provide-support-for-test-netwo
https://www.reddit.com/r/ethereum/comments/669dmp/best_wallets_for_erc20_tokens/
https://ethereum.stackexchange.com/questions/15806/where-is-the-erc-20-token-code?newreg=bcb0e4522a1e476398d8b842a1aa584e
https://github.com/ConsenSys/Tokens

I would like to better understand what’s involved in building native support for tokens into Balance Open.

**Comment by ricburton** [comment]
https://theethereum.wiki/w/index.php/ERC20_Token_Standard
https://github.com/ethereum/EIPs

This was an Ethereum Improvement Proposal (EIP). So many acronyms. This has to be the highest value one of all time! 

https://github.com/ethereum/EIPs/pull/610

**Comment by einsteinx2** [comment]
Closing this in lieu of Support for raw wallet addresses #87 since that will include support for tokens.
