### ISSUE TITLE
[Idea] Support for ShapeShift

### ISSUE THREAD

**Issue by ricburton** [balancemymoney/balance-open#59]
ShapeShift partners with lots of people to create an exchange for digital assets. I just listened to it's founder, Eric Voorhees, speak on this podcast.

Epicenter – Podcast on Blockchain, Ethereum, Bitcoin and Distributed Technologies: #190 Erik Voorhees: Prism – The World’s First Portfolio Market Platform
https://overcast.fm/+BuoRJjmOE

I want to dive into their technology more.

**Comment by ricburton** [comment]
https://info.shapeshift.io/api

**Comment by wolffan** [comment]
I'll be closing this one since we have now a Milestone for it :).
And move the podcast to the internal twist podcast
