### ISSUE TITLE
GDAX Client Side Auth

### ISSUE THREAD

**Issue by reddavis** [balancemymoney/balance-open#72]
# Overview

GDAX does not appear to support OAuth. 

The user needs to create an API key from their GDAX settings. After creating a key, the user will then have these 3 things:

- Key
- Secret
- Passphase

These are all required for API access.

Auth flow for the user will look something like this:

- User chooses to add GDAX
- User inputs the key, secret and passphase
- Success!

All requests to GDAX must contain these headers:

- Key
- Signature
- Timestamp
- Passphase

More details about this [here](https://docs.gdax.com/#creating-a-request)

**Comment by einsteinx2** [comment]
Done
