### ISSUE TITLE
GDAX login UI

### ISSUE THREAD

**Issue by wolffan** [balancemymoney/balance-open#74]
This is a 3 field UI for login into GDAX.

Secret
Key
Passhprase

**Comment by ricburton** [comment]
I’ll get on this now :)

**Comment by ricburton** [comment]
Here’s the Figma link: https://www.figma.com/file/KjGxL02nHwM8ZklmroLQSUoL/GDAX-login-UI-74

**Comment by ricburton** [comment]
@wolffan do you have a verified GDAX account? Mine is still being verified. I want to see what the API page looks like.<img src='https://shipusercontent.com/d41317a2f4cf269a3d764a11b69b3733/Screen%20Shot%202017-08-16%20at%2014.32.32.png' title='Screen Shot 2017-08-16 at 14.32.32.png' width=188>

https://www.gdax.com/settings/api

**Comment by ricburton** [comment]
<img src='https://shipusercontent.com/5bfe364d930b09962b6a95db33933b51/gdax%20connection%20first%20pass%402x.png' title='gdax connection first pass@2x.png' width=522>


OK I am happy with this for a first pass.

**Comment by wolffan** [comment]
@ricburton I do not have a GDAX verified account (only Poloniex)

BTW for now i'm reusing what we have on Bal, so it will be similar to this one, but not exact.

**Comment by einsteinx2** [comment]
This is done for now. Will update if/when we get a new design spec.
