### ISSUE TITLE
Poloniex Login UI

### ISSUE THREAD

**Issue by wolffan** [balancemymoney/balance-open#75]
We need two fields to add APIKey + Secret

**Comment by ricburton** [comment]
I’ll post the design updates in here: https://www.figma.com/file/M5R7rjUAhO35gzo5rNkkSTdv/Poloniex-Login-UI-75

It’ll be really similar to GDAX.

**Comment by einsteinx2** [comment]
This is done for now. Will update if/when we get a new design spec.

**Comment by cjdowner** [comment]
I have a suggestion to improve the UX of this – because I didn't know where to look to enable my API keys on Poloniex. Shall I file a separate issue?

**Comment by ricburton** [comment]
Great point I think we should included a link out to the right URL for where you can find these.

https://poloniex.com/apiKeys ( https://poloniex.com/apiKeys )

There is also a bunch of back-and-forth where you need to confirm the request for API keys from your email address.

Richard

Sent via Superhuman ( https://sprh.mn/?vip=burtonic@gmail.com )
