### ISSUE TITLE
Add currency price chart / display

### ISSUE THREAD

**Issue by wolffan** [balancemymoney/balance-open#77]
Poloniex offers free api calls (no auth).
We could use this to show certain variations and market prices on bitcoin, eth... etc right away (no auth needed)
Also good idea for getting users maybe?

**Comment by ricburton** [comment]
That's a really cool idea. I'll start thinking about a UI for it.

**Comment by einsteinx2** [comment]
Generalized the title

**Comment by einsteinx2** [comment]
Tentatively placed in 1.0 milestone

**Comment by einsteinx2** [comment]
Bumping to 1.1

**Comment by einsteinx2** [comment]
Already built in 1.0.
