### ISSUE TITLE
[Idea] Add support for Coinbase Send

### ISSUE THREAD

**Issue by ricburton** [balancemymoney/balance-open#80]
I would love to be able to quickly send money to people from Balance. A quick way to get started here would be by adding support for the ability for people to send money from Coinbase.

<img src='https://shipusercontent.com/52508a3a0bc058368d5a98f2eb787193/Screen%20Shot%202017-08-07%20at%2002.07.28.png' title='Screen Shot 2017-08-07 at 02.07.28.png' width=535>

If I could send money from my mac as quickly as I can send email, that would be amazing. 

Right now, due to very valid security considerations, Coinbase often requires you to verify your browser through an email. This roundabout trip to log in takes a long time and decreases the number of times I send money from my Mac. Conversely on iOS, where TouchID authentication is available, I send money much more often.

**Comment by ricburton** [comment]
We could also fix this: https://cl.ly/2R3f3J1m2C3G

The top currency gets reset when you change the wallet you are sending from, which annoying. I think there is a better UI design in here.

**Comment by einsteinx2** [comment]
Sending in general will need it's own TLF with various facets like: api token security, UI design, etc. Once we get 1.0 out the door in a few weeks, let's make this a top priority to flesh out.

**Comment by einsteinx2** [comment]
Closing this in lieu of Add the ability to send money via coinbase #42
