### ISSUE TITLE
My onboarding experience

### ISSUE THREAD

**Issue by kristinatauch** [balancemymoney/balance-open#83]
I downloaded BalanceOpen.app.0.9.2.zip from https://github.com/balancemymoney/balance-open/releases and then opened it in Applications and dragged it to the Menu Bar on the bottom. Tried clicking on it to open, but it didn't. Didn't realise that there is the little icon in the top right corner.

**Comment by einsteinx2** [comment]
Not sure why we're not doing this in Balance Open, but in Balance we specifically make sure to open the menu bar app on launch so that it's clear where it lives.

As soon as I get back from Uganda and get the two apps' code bases merged, this issue will be fixed. Leaving this issue open until then.

**Comment by wolffan** [comment]
I confirm the issue.
At least first time opening we don't show anything.

**Comment by wolffan** [comment]
This will fix this issue https://github.com/balancemymoney/balance-open/pull/86

Thanks @kristinatauch and @einsteinx2 you can take a look
