### ISSUE TITLE
No coinbase accounts shown (waiting for release to fix)

### ISSUE THREAD

**Issue by n6g7** [balancemymoney/balance-open#84]
Hi,

Just installed this yesterday evening (after the ethmeetup!), when opening the app and logging in to Coinbase I see this:
<img width="414" alt="" src="https://user-images.githubusercontent.com/3386177/29117513-5a752b62-7cf6-11e7-8dce-1c38b5d4fb68.png">

I was expecting to see my BTC, ETH and euro wallets here.

This appears in my console whenever I open the app:
<img width="887" alt="" src="https://user-images.githubusercontent.com/3386177/29117523-664197fa-7cf6-11e7-9650-8e2c1c0c374b.png">

Might be related to the macOS keychain. Any idea what the exception 17 is?

Edit: forgot to say I'm running 0.9.2!

**Comment by einsteinx2** [comment]
Thanks for the bug report! It does indeed look like something weird is going on with the keychain. I'm currently traveling in Uganda, but @wolffan can take a look at this.

**Comment by wolffan** [comment]
Thanks @n6g7 
Two questions:
- did you download the app or installed it from github + xcode?
- Are you by any chance not a US/UK locale (that's the keyboard)

**Comment by n6g7** [comment]
@wolffan 
- I downloaded the app from https://github.com/balancemymoney/balance-open/releases
- Yes I use the French locale/keyboard layout

**Comment by LucaTNT** [comment]
Same here!

(Italian Keyboard, macOS language set to US English)

**Comment by wolffan** [comment]
@n6g7 @LucaTNT thanks for the feedback :D.
We detected and fixed the problem :).

But we haven't made a new release. As soon as we release a new version this will be fixed.
Apologies for this, I'll let you know when we make a new release!

**Comment by n6g7** [comment]
Amazing, thanks @wolffan!
Any timeframe for the next release?

**Comment by wolffan** [comment]
@n6g7 Next week :). Look for Wednesday (although If I can make this on Monday I will).

**Comment by n6g7** [comment]
Hi @wolffan, any news about this upcoming release? :)
Can't wait to use this app!

**Comment by wolffan** [comment]
Doing a build as we speak @n6g7  :)

**Comment by wolffan** [comment]
can you give feedback when you can @n6g7 ? version is live :)

**Comment by n6g7** [comment]
@wolffan Amazing, it's working now!
Thanks guys, keep those releases coming! :)

**Comment by wolffan** [comment]
Awesome :D
