### ISSUE TITLE
Support for raw wallet addresses

### ISSUE THREAD

**Issue by ricburton** [balancemymoney/balance-open#87]
It would really help if we could add a "watcher" for raw addresses. We could look into APIs for monitoring the balances of Bitcoin, Ether, and other digital asset addresses.

That way we could really speed up the exchange process.

**Comment by einsteinx2** [comment]
Raimon is working on this now.

**Comment by einsteinx2** [comment]
This is actually 2 tasks, one for ETH addresses and one for Bitcoin.

**Comment by wolffan** [comment]
has been merged 🎉
