### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by ricburton** [balancemymoney/balance-open#88]
I am trying to set up Balance Open on a new machine. I want to share my issues here so that anyone who having similar problems can find this GitHub issue and refer to it. I have tried to fix the problem on my own but I have reached a roadblock.

I downloaded the project and got this error in XCode:
> 
> “Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

<img src='https://shipusercontent.com/b6cd682fdbe5d156f4b9404d569d801e/Screen%20Shot%202017-08-16%20at%2013.53.40.png' title='Screen Shot 2017-08-16 at 13.53.40.png' width=1680>

I went to update my libraries with carthage and got this error:

> Build Failed
> 	Task failed with exit code 65:
> 	/usr/bin/xcrun xcodebuild -workspace /Users/richardburton/balance-open/Carthage/Checkouts/SnapKit/SnapKit.xcworkspace -scheme SnapKit -configuration Release -derivedDataPath /Users/richardburton/Library/Caches/org.carthage.CarthageKit/DerivedData/SnapKit/ae3b03640d275587a3717fbc19b4d62f20c13b04 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build
> 
> This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/d6/80xps8ss6rv3tz9zn393hgqr0000gn/T/carthage-xcodebuild.SNNoE6.log

<img src='https://shipusercontent.com/5e3f8bc860bef776a159fa29a7d61303/Screen%20Shot%202017-08-16%20at%2013.54.48.png' title='Screen Shot 2017-08-16 at 13.54.48.png' width=969>

**Comment by wolffan** [comment]
@ricburton this problem is related to Xcode version.
Make sure you have the last beta AND that in your terminal typing:
`xcode-select -p`
shows the following:
`/Applications/Xcode-beta.app/Contents/Developer`

Note the `Xcode-beta` which is making sure the command line tools in terminal point to new xcode (for compilation).
If it's not the case, then you'll need to:
`xcode-select -s /Applications/Xcode-beta.app/Contents/Developer/`

let me know if it works

**Comment by einsteinx2** [comment]
Yeah right now Xcode 9 Beta 6 is required to compile the highlander branch, master 14 days ago probably required Beta 5 to compile. You should never need to recompile Carthage frameworks. Once Xcode 9 is officially released this will be simpler as betas won't be coming out all the time and the Swift 4 API will be stable.

**Comment by einsteinx2** [comment]
Closing this issue as the error in this specific issue is from using Xcode 8. Xcode 9 beta 6 (currently) is required.
