### ISSUE TITLE
[Idea] Summarise coin balances

### ISSUE THREAD

**Issue by punkstar** [balancemymoney/balance-open#94]
My use case for Balance at the moment is to keep track of what my coin balances look like in GBP.  This isn't made easy by the fact that I've got balances split up across multiple wallets in my Coinbase account, meaning I've got to add them up myself - and I'm lazy!

![screen shot 2017-08-23 at 12 08 10](https://user-images.githubusercontent.com/179072/29613201-d972dcb4-87fc-11e7-8449-46d8b7c40dd7.png)

I can see this problem getting worse as I add my other accounts at other exchanges.

I'd find some kind of "Net Worth" summary useful, somewhere I can see the total BTC / ETH / etc that I own, along with a conversion into GBP.

**Comment by ricburton** [comment]
Totally agree. Master currency and total balance is coming very soon.

**Comment by einsteinx2** [comment]
Tentatively placing in 1.0 milestone

**Comment by einsteinx2** [comment]
Bumping to 1.1, but this is definitely a priority.

**Comment by wolffan** [comment]
@punkstar we just released a new beta, you can head to https://github.com/balancemymoney/balance-open/releases/ and download it. So you have this feature (in fact not just for coinbase, but for all he accounts you merge in). 
I'll close this one :) (also you can change the currency you want to see your funds in)
