### ISSUE TITLE
Looses credentials when laptop resumes from sleep

### ISSUE THREAD

**Issue by davidolrik** [balancemymoney/balance-open#95]
When my laptop resumes, and my local proxy isn't yet ready the app will loose my credentials, requiring a re-authorization on Coinbase.

I'm guessing the call to Coinbase is getting a 503 from the proxy, causing it to forget the authorization.

BalanceOpen 0.9.3 (4)
macOS 10.12.6 (16G29)

**Comment by davidolrik** [comment]
It actually doesn't loose the credentials.

But this dialog is open when I resume:

<img width="744" alt="napkin 24-08-17 9 54 29 pm" src="https://user-images.githubusercontent.com/1990/29685785-d49561e2-8916-11e7-9c7b-55c021b7e47f.png">

The menubar item still works. I can't quit the app, but I can kill it - and after a restart of the app everything is ok again.

**Comment by ricburton** [comment]
That’s not good at all. We’ll follow up ASAP.

Richard

**Comment by einsteinx2** [comment]
Looking into this now.

**Comment by einsteinx2** [comment]
Looks like there's too issues here. One is a known issue in the Reachability library we're using which detects network availability. Right now it only checks if the network is active, not if connections to particular sites work. So when the app starts, it checks for network access, and then syncs. However in your case, the network isn't actually available yet.

The second, more direct, issue is in the Coinbase error handling. Right now it treats all errors the same, when it should be handling this error more gracefully.

We'll have a fix in the next release. Thanks for the report!

**Comment by einsteinx2** [comment]
I've created action tickets to fix this for 1.0 release.

Replace Reachability framework with one that correctly determines network status #99
Fully implement Coinbase API error handling #98
